name: Test Coveralls

on: ["push", "pull_request"]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Coverage
      run: |
        npm ci
        npm run coverage

    - name: Coveralls
      uses: coverallsapp/github-action@09b709cf6a16e30b0808ba050c7a6e8a5ef13f8d # master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
